### ISSUE TITLE
Seed 3-up card bar chart throws width error

### ISSUE THREAD

**Issue by lrbridge** [PredixDev/px-simple-bar-chart#5]
In the latest [predix-seed live demo](https://predix-seed-dev.grc-apps.svc.ice.ge.com/dashboards), the chart is throwing an error even though the width should be fine.

<img width="1386" alt="screen shot 2015-12-08 at 4 28 50 pm" src="https://cloud.githubusercontent.com/assets/6046316/11672877/05e118b2-9dc9-11e5-8081-46818903db2c.png">

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by yashdoshi89** [comment]
This bug would have been caused because of on going development of the charts. It was fixed in px-simple-bar-chart so it would not show up now in predix-seed.
