### ISSUE TITLE
Legends are not shown

### ISSUE THREAD

**Issue by ugurk** [PredixDev/px-simple-bar-chart#9]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

Legends should be shown on chart. It works as expected for multi-series.

## Steps to reproduce the problem:

See demo: https://www.predix-ui.com/#/components/px-simple-bar-chart/

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Chrome v.56 on Windows 7

## Screenshots (_optional, but very helpful_):

![](http://i.imgur.com/zTiTVLR.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
I thought this was an issue because the demo page has 4 demo labels but only 1 series for that example, but changing the number of labels didn't fix it. It may be programmed intentionally to not show the legend when there is only one series, I'm not sure.

**Comment by nonmetalhail** [comment]
That's what I think too. I believe the labels are only for when you are using multi-series.

**Comment by ugurk** [comment]
I checked the code:

```javascript
        _requireLegend: function() {
            // legend is required if any of the
            return this.chartData.length > 1;
        }
```

According to this function it seems legends are only available for multi-series.
Documentation should include this information.

It would be great if single series chart has legends too.

**Comment by randyaskin** [comment]
I've updated the function as follows:

```
_requireLegend: function() {
            // legend is required if legend labels are supplied, otherwise omitted
            return this.legendLabels.length > 0;
        },
```
